/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2025-03-20 06:26:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "include/link.html", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/home.css\">\r\n");
      out.write("<script src=\"js/home.js\" defer></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class='wrap'>\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "include/header.html", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<div id=\"contents\">\r\n");
      out.write("			<div class=\"homepage\">\r\n");
      out.write("				<section id=\"home\">\r\n");
      out.write("					<h5>내 정보 🚀</h5>\r\n");
      out.write("					<div class=\"login flex\">\r\n");
      out.write("						<figure>\r\n");
      out.write("							<img src=\"img2/ex.jpg\" alt=\"home_login_img\">\r\n");
      out.write("						</figure>\r\n");
      out.write("						<div class=\"homeLoginInfo\">\r\n");
      out.write("							<p class=\"name\">송택호</p>\r\n");
      out.write("							<div class=\"genderAndage\">\r\n");
      out.write("								<span>남</span> <span>10세</span>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"myGroup\">\r\n");
      out.write("								<span style=\"padding-right: 20px;\">내 그룹 <span\r\n");
      out.write("									class=\"myGroupNum\">5</span></span> <span>문의 <span\r\n");
      out.write("									class=\"myGroupNum\">12</span></span>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"myPageLink\">\r\n");
      out.write("							<div class='myPagewrap'>\r\n");
      out.write("								<p>마이페이지</p>\r\n");
      out.write("								<span><img src=\"img2/next.png\" alt=\"\"></span>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("	\r\n");
      out.write("					<!-- 로그인 전 -->\r\n");
      out.write("					<div class=\"beforeLogin\">\r\n");
      out.write("						<h3>로그인 하러가기</h3>\r\n");
      out.write("						<p>로그인하고 피움 서비스를 자유롭게 이용해보세요.</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</section>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("				<section class=\"announcement\">\r\n");
      out.write("					<h5>공지사항 📢</h5>\r\n");
      out.write("					<div class=\"swiper mySwiper2\">\r\n");
      out.write("						<div class=\"swiper-wrapper flex\">\r\n");
      out.write("							<div class=\"swiper-slide\">\r\n");
      out.write("								<h2>[안내] 네이버웍스 경영지원 성과평가 서비스 베타 오픈</h2>\r\n");
      out.write("								<p>yyyy년 MM월 dd일</p>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"swiper-slide\">\r\n");
      out.write("								<h2>[사전 안내 2차] 상반기 Windows WORKS Drive탐색기 신규 업데이트 주요 변경 사항</h2>\r\n");
      out.write("								<p>yyyy년 MM월 dd일</p>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"swiper-slide\">\r\n");
      out.write("								<h2>[교육] 네이버웍스 클로바노트 사용자 무료 교육 안내ㅣ25년 2월 13일(목)</h2>\r\n");
      out.write("								<p>yyyy년 MM월 dd일</p>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"swiper-slide\">\r\n");
      out.write("								<h2>네이버웍스 경영지원 정기 업데이트 소식</h2>\r\n");
      out.write("								<p>yyyy년 MM월 dd일</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("	\r\n");
      out.write("				</section>\r\n");
      out.write("	\r\n");
      out.write("				<section class=\"CapsuleReveal\">\r\n");
      out.write("					<h5>타입캡슐 ⌛</h5>\r\n");
      out.write("					<div class=\"swiper mySwiper3\">\r\n");
      out.write("						<div class=\"swiper-wrapper\">\r\n");
      out.write("							<div class=\"swiper-slide\">\r\n");
      out.write("								<div class=\"group\">\r\n");
      out.write("									<div class=\"groupinfo\">\r\n");
      out.write("										<div class=\"groupCreator\">\r\n");
      out.write("											<img src=\"img2/ex.jpg\" alt=\"#\">\r\n");
      out.write("											<p>rivermoon___</p>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"groupDate\">24.09.08 ~ 24.09.19</div>\r\n");
      out.write("									</div>\r\n");
      out.write("	\r\n");
      out.write("									<div class=\"groupmember\">\r\n");
      out.write("										<span><img src=\"img2/ex.jpg\" alt=\"#\" class=\"member1\"></span>\r\n");
      out.write("										<span><img src=\"img2/ex.jpg\" alt=\"#\" class=\"member2\"></span>\r\n");
      out.write("										<span><img src=\"img2/ex.jpg\" alt=\"#\" class=\"member3\"></span>\r\n");
      out.write("										<span><img src=\"img2/ex.jpg\" alt=\"#\" class=\"member4\"></span>\r\n");
      out.write("										<span><img src=\"img2/ex.jpg\" alt=\"#\" class=\"member5\"></span>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"grouptag\">\r\n");
      out.write("										<p>#활발</p>\r\n");
      out.write("										<p>#여름</p>\r\n");
      out.write("										<p>#카페</p>\r\n");
      out.write("										<p>#맑음</p>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"swiper-slide\">\r\n");
      out.write("								<div class=\"group\">\r\n");
      out.write("									<div class=\"groupinfo\">\r\n");
      out.write("										<div class=\"groupCreator\">\r\n");
      out.write("											<img src=\"img2/ex.jpg\" alt=\"#\">\r\n");
      out.write("											<p>rivermoon___</p>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"groupDate\">24.09.08 ~ 24.09.19</div>\r\n");
      out.write("									</div>\r\n");
      out.write("	\r\n");
      out.write("									<div class=\"groupmember\">\r\n");
      out.write("										<span><img src=\"img2/ex.jpg\" alt=\"#\" class=\"member1\"></span>\r\n");
      out.write("										<span><img src=\"img2/ex.jpg\" alt=\"#\" class=\"member2\"></span>\r\n");
      out.write("										<span><img src=\"img2/ex.jpg\" alt=\"#\" class=\"member3\"></span>\r\n");
      out.write("										<span><img src=\"img2/ex.jpg\" alt=\"#\" class=\"member4\"></span>\r\n");
      out.write("										<span><img src=\"img2/ex.jpg\" alt=\"#\" class=\"member5\"></span>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"grouptag\">\r\n");
      out.write("										<p>#활발</p>\r\n");
      out.write("										<p>#여름</p>\r\n");
      out.write("										<p>#카페</p>\r\n");
      out.write("										<p>#맑음</p>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"swiper-slide\">\r\n");
      out.write("								<div class=\"group\">\r\n");
      out.write("									<div class=\"groupinfo\">\r\n");
      out.write("										<div class=\"groupCreator\">\r\n");
      out.write("											<img src=\"img2/ex.jpg\" alt=\"#\">\r\n");
      out.write("											<p>rivermoon___</p>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"groupDate\">24.09.08 ~ 24.09.19</div>\r\n");
      out.write("									</div>\r\n");
      out.write("	\r\n");
      out.write("									<div class=\"groupmember\">\r\n");
      out.write("										<span><img src=\"img2/ex.jpg\" alt=\"#\" class=\"member1\"></span>\r\n");
      out.write("										<span><img src=\"img2/ex.jpg\" alt=\"#\" class=\"member2\"></span>\r\n");
      out.write("										<span><img src=\"img2/ex.jpg\" alt=\"#\" class=\"member3\"></span>\r\n");
      out.write("										<span><img src=\"img2/ex.jpg\" alt=\"#\" class=\"member4\"></span>\r\n");
      out.write("										<span><img src=\"img2/ex.jpg\" alt=\"#\" class=\"member5\"></span>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"grouptag\">\r\n");
      out.write("										<p>#활발</p>\r\n");
      out.write("										<p>#여름</p>\r\n");
      out.write("										<p>#카페</p>\r\n");
      out.write("										<p>#맑음</p>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"swiper-slide\">\r\n");
      out.write("								<div class=\"group\">\r\n");
      out.write("									<div class=\"groupinfo\">\r\n");
      out.write("										<div class=\"groupCreator\">\r\n");
      out.write("											<img src=\"img2/ex.jpg\" alt=\"#\">\r\n");
      out.write("											<p>rivermoon___</p>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"groupDate\">24.09.08 ~ 24.09.19</div>\r\n");
      out.write("									</div>\r\n");
      out.write("	\r\n");
      out.write("									<div class=\"groupmember\">\r\n");
      out.write("										<span><img src=\"img2/ex.jpg\" alt=\"#\" class=\"member1\"></span>\r\n");
      out.write("										<span><img src=\"img2/ex.jpg\" alt=\"#\" class=\"member2\"></span>\r\n");
      out.write("										<span><img src=\"img2/ex.jpg\" alt=\"#\" class=\"member3\"></span>\r\n");
      out.write("										<span><img src=\"img2/ex.jpg\" alt=\"#\" class=\"member4\"></span>\r\n");
      out.write("										<span><img src=\"img2/ex.jpg\" alt=\"#\" class=\"member5\"></span>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"grouptag\">\r\n");
      out.write("										<p>#활발</p>\r\n");
      out.write("										<p>#여름</p>\r\n");
      out.write("										<p>#카페</p>\r\n");
      out.write("										<p>#맑음</p>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"swiper-slide\">\r\n");
      out.write("								<div class=\"group\">\r\n");
      out.write("									<div class=\"groupinfo\">\r\n");
      out.write("										<div class=\"groupCreator\">\r\n");
      out.write("											<img src=\"img2/ex.jpg\" alt=\"#\">\r\n");
      out.write("											<p>rivermoon___</p>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"groupDate\">24.09.08 ~ 24.09.19</div>\r\n");
      out.write("									</div>\r\n");
      out.write("	\r\n");
      out.write("									<div class=\"groupmember\">\r\n");
      out.write("										<span><img src=\"img2/ex.jpg\" alt=\"#\" class=\"member1\"></span>\r\n");
      out.write("										<span><img src=\"img2/ex.jpg\" alt=\"#\" class=\"member2\"></span>\r\n");
      out.write("										<span><img src=\"img2/ex.jpg\" alt=\"#\" class=\"member3\"></span>\r\n");
      out.write("										<span><img src=\"img2/ex.jpg\" alt=\"#\" class=\"member4\"></span>\r\n");
      out.write("										<span><img src=\"img2/ex.jpg\" alt=\"#\" class=\"member5\"></span>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"grouptag\">\r\n");
      out.write("										<p>#활발</p>\r\n");
      out.write("										<p>#여름</p>\r\n");
      out.write("										<p>#카페</p>\r\n");
      out.write("										<p>#맑음</p>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"swiper-slide\">\r\n");
      out.write("								<div class=\"group\">\r\n");
      out.write("									<div class=\"groupinfo\">\r\n");
      out.write("										<div class=\"groupCreator\">\r\n");
      out.write("											<img src=\"img2/ex.jpg\" alt=\"#\">\r\n");
      out.write("											<p>rivermoon___</p>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"groupDate\">24.09.08 ~ 24.09.19</div>\r\n");
      out.write("									</div>\r\n");
      out.write("	\r\n");
      out.write("									<div class=\"groupmember\">\r\n");
      out.write("										<span><img src=\"img2/ex.jpg\" alt=\"#\" class=\"member1\"></span>\r\n");
      out.write("										<span><img src=\"img2/ex.jpg\" alt=\"#\" class=\"member2\"></span>\r\n");
      out.write("										<span><img src=\"img2/ex.jpg\" alt=\"#\" class=\"member3\"></span>\r\n");
      out.write("										<span><img src=\"img2/ex.jpg\" alt=\"#\" class=\"member4\"></span>\r\n");
      out.write("										<span><img src=\"img2/ex.jpg\" alt=\"#\" class=\"member5\"></span>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"grouptag\">\r\n");
      out.write("										<p>#활발</p>\r\n");
      out.write("										<p>#여름</p>\r\n");
      out.write("										<p>#카페</p>\r\n");
      out.write("										<p>#맑음</p>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"swiper-pagination\" style=\"top: 3px;\"></div>\r\n");
      out.write("					</div>\r\n");
      out.write("	\r\n");
      out.write("				</section>\r\n");
      out.write("	\r\n");
      out.write("				<section class=\"memory\">\r\n");
      out.write("					<h5>추억을 함께한 사람 💫</h5>\r\n");
      out.write("					<div class=\"memoryList\">\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li><img src=\"img2/ex.jpg\" alt=\"memoryImages\">\r\n");
      out.write("								<p>김대영</p></li>\r\n");
      out.write("							<li><img src=\"img2/ex.jpg\" alt=\"memoryImages\">\r\n");
      out.write("								<p>김현수</p></li>\r\n");
      out.write("							<li><img src=\"img2/ex.jpg\" alt=\"memoryImages\">\r\n");
      out.write("								<p>김나연</p></li>\r\n");
      out.write("							<li><img src=\"img2/ex.jpg\" alt=\"memoryImages\">\r\n");
      out.write("								<p>송택호</p></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("	\r\n");
      out.write("					<div class=\"beforeLogin-memory\">\r\n");
      out.write("						<img src=\"img/time.gif\" alt=\"time\">\r\n");
      out.write("						<p>로그인 하시고 많은 사람들과 추억을 공유하세요!</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</section>\r\n");
      out.write("	\r\n");
      out.write("				<section class=\"topViews\">\r\n");
      out.write("					<h5>TOP 조회수 👀</h5>\r\n");
      out.write("					<div class=\"viewBox\">\r\n");
      out.write("						<div class=\"image\">\r\n");
      out.write("							<!-- <img src=\"/img/backgorund.jpg\" alt=\"topViewsImg\"> -->\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"viewInfo\">\r\n");
      out.write("							<p>타임캡슐 제목</p>\r\n");
      out.write("							<div>\r\n");
      out.write("								<span><img src=\"img2/person.png\" alt=\"personIcon\"></span> <span\r\n");
      out.write("									style=\"font-size: 15px; color: var(--text-color);\">8 / 15</span>\r\n");
      out.write("							</div>\r\n");
      out.write("	\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"viewIcon\">\r\n");
      out.write("							<img src=\"img2/next.png\" alt=\"viewNextIcon\">\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</section>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "include/footer.html", out, false);
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
